### PR TITLE
Add a proposal for issue triaging

### LINKED ISSUE #11723: NuGet's OSS Issue Triage Policy
Hi friends,

NuGet is adding an issue triage policy to help you understand how we work within OSS. You can get an idea of how we triage issues and what you can expect when you file an issue on our repositories.

https://github.com/NuGet/Home/pull/11719

We'd love any and all feedback on it! 🎉

### PR DESCRIPTION
**Pull request by heng-liu**
The purpose of this proposal is to help establish issue triaging policy for NuGet/Home.
This proposal is influenced by https://github.com/microsoft/vscode/wiki/Issues-Triaging and https://github.com/dotnet/runtime/blob/main/docs/issues-pr-management.md.

[Rendered Proposal](https://github.com/NuGet/Home/blob/1aa54af6d6ab14ba358e4fb49c331930fd943815/proposed/2022/Issue-triaging.md)

We'd love to hear from the community. Pls add your feedback in the comments, thanks!
We will target to publish it in May, 2022.

Please 👍 or 👎 this comment to help us with the direction of this proposal & leave as much feedback/questions/concerns as you'd like on this issue itself and we will get back to you shortly.

Thank You 🎉

Fixes https://github.com/NuGet/Home/issues/11723

### CODE REVIEW

**Comment by skofman1** [comment]
Great write-up @heng-liu !!! The one suggestion I would have will be to add the numbers mentioned in this paragraph to the diagram.
> The feature is under consideration. A Pipeline:Under Consideration label is added. A bot monitors the issues having Pipeline:Under Consideration label. If an issue surpasses the **5 up-votes in 90** days, the bot adds Triage:NeedsTriageDiscussion label and we will have a second triaging process. If an issue has been added Pipeline:Under Consideration label with **less than 5 up-votes for more than 90 days**, the bot will close the issue. During the second triaging process, we will do more analysis to determine the cost/benefit. We will add Pipeline:Backlog label to the issue if we decide to accept the issue. Otherwise, the issue will be closed with an explanation why we do so.

**Review by JonDouglas — APPROVED** [review]
This is a great start, thank you for writing it!

**Review by jeffkl — APPROVED** [review]

**Review by nkolev92 — APPROVED** [review]

**Comment by nkolev92** [comment]
Should we merge this? :)

**Comment by heng-liu** [comment]
Hi @nkolev92 , thanks for reminding! We'd like to have it reviewed by the community so might wait for about 30 days or so?

**Comment by nkolev92** [comment]
oh yep, the description says May.

**Comment by JonDouglas** [comment]
Ready to merge?

**Comment by heng-liu** [comment]
> Great write-up @heng-liu !!! The one suggestion I would have will be to add the numbers mentioned in this paragraph to the diagram.
> 
> > The feature is under consideration. A Pipeline:Under Consideration label is added. A bot monitors the issues having Pipeline:Under Consideration label. If an issue surpasses the **5 up-votes in 90** days, the bot adds Triage:NeedsTriageDiscussion label and we will have a second triaging process. If an issue has been added Pipeline:Under Consideration label with **less than 5 up-votes for more than 90 days**, the bot will close the issue. During the second triaging process, we will do more analysis to determine the cost/benefit. We will add Pipeline:Backlog label to the issue if we decide to accept the issue. Otherwise, the issue will be closed with an explanation why we do so.

Sorry for the late reply! This paragraph is about how we triage feature requests. For bugs, we also collect upvotes but we won't close bugs after 90 days(same with vscode). 
We're considering doing some adhoc experiment later(like what dotnet runtime did), to close stale, low-upvotes, and `under consideration` bugs (but we haven't defined the standards yet).
So there is uncertain info in the description and might be long if adding all those into the diagram. 
I'll try to address this when the adhoc experiment is done :)

**Comment by heng-liu** [comment]
> Ready to merge?

Thanks for asking! 
I think so. I'll merge it by EOD today if there is no concern. //cc @aortiz-msft

**Pull request merged**
