### PR TITLE
Add design for dotnet list package --verbosity

### PR DESCRIPTION
**Pull request by joelverhagen**
Related to https://github.com/NuGet/Home/issues/9600.

See the Markdown view for details and context:
image

### CODE REVIEW

**Comment by anangaur** [comment]
Can you post output for default (minimal?), normal and other verbosity levels?

**Comment by joelverhagen** [comment]
@anangaur - added that to the end of the spec

**Comment by anangaur** [comment]
To me the normal verbosity should be the default and the amount of normal verbosity should be same as what is minimal today :)

However, I see that minimal is default verbosity level for dotnet implying customers see the right verbosity using dotnet.exe. However, if a command is also available with nuget.exe and MSBuild.exe does it mean that customers would see different/more verbose output with these tools? If so, this is odd.

**Comment by joelverhagen** [comment]
> To me the normal verbosity should be the default and the amount of normal verbosity should be same as what is minimal today :)

Yes normal seems like the default word, but the other `dotnet` commands have already made this decision. It just so happens that the default verbosity (minimal) will cause the output of `dotnet list package` to look the same after this change is implemented. So that works in our favor it thing. I believe the right user experience is to hide HTTP messages but default.

I'll note that this does align with nuget.exe list (which has entirely different behavior, but the closest match to dotnet list package). In short nuget.exe list also hides HTTP by default but shows it if you increase verbosity. So that's matching-ish.

> However, if a command is also available with nuget.exe and MSBuild.exe does it mean that customers would see different/more verbose output with these tools?

This command is only available on the `dotnet` CLI so it's a non-issue here.

**Review by nkolev92 — APPROVED** [review]
This is a beautifully written and very detailed spec. 

👏 👏 👏 👏 

I am personally not concerned about the extra logs. 
Warnings should be surfaced to the customer.

**Pull request merged**
