### PR TITLE
Display Target Framework info on NuGet.org

### PR DESCRIPTION
**Pull request by jcjiang**
Introduction of our concept for displaying target framework information on NuGet.org, which allows a developer to see at a glance whether a package is supported by their framework.

[Find the rendered spec here.](https://github.com/NuGet/Home/blob/aa324012cf1782d784b707f159f38d52a7ad25ce/proposed/2021/NuGetOrgTFMDropdownBadges.md)

🎉📦Please provide your comments, concerns, and feedback within this PR. 📦🎉

### CODE REVIEW

**Comment by JonDouglas** [comment]
Thank you so much for the contribution to NuGet!

We'll leave this proposal open for the next couple weeks to get feedback from the .NET community & respective teams & we'll do a quick internal review after!

If you're seeing this message, please 👍 or provide your feedback on this proposal in this PR as to why we should or shouldn't do this.

Thank you everyone!

**Comment by JonDouglas** [comment]
@jcjiang Can we assign respective reviewers & get approval to merge this in?

**Comment by hickford** [comment]
See also https://github.com/NuGet/NuGetGallery/issues/3098 "search by framework"

**Comment by hickford** [comment]
If I understand correctly, this pull request is a fix for https://github.com/NuGet/NuGetGallery/issues/4843 "Gallery should show which frameworks a package is compatible with"

**Comment by JonDouglas** [comment]
@hickford Yes that is correct. We're working on wrapping up this PR & shipping the work.

https://github.com/NuGet/NuGetGallery/pull/8867

**Comment by zivkan** [comment]
@JonDouglas @clairernovotny Who is taking over this now that @jcjiang has left NuGet?

**Comment by JonDouglas** [comment]
@zivkan I will merge this work as it was recently merged in PR. Thanks

**Review by JonDouglas — APPROVED** [review]
Approving as work has completed and will be shipped shortly.

**Pull request merged**
