### PR TITLE
Proposal of consolidating user wide NuGet.Config files on Linux/Mac

### PR DESCRIPTION
**Pull request by heng-liu**
Design for https://github.com/NuGet/Home/issues/4413

### CODE REVIEW

**Review by zkat — COMMENTED** [review]
IMO:

* We should comply with the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) for config directories, aka use the env var `$XDG_CONFIG_HOME`, which will default to `~/.config` **on Linux**.
* **For macOS**, we should conform to their [Standard Directories](https://developer.apple.com/library/archive/documentation/General/Conceptual/MOSXAppProgrammingGuide/AppRuntime/AppRuntime.html) guidance (search for "Important App Directories"), which means we would use `~/Library/Application Support/NuGet/NuGet.Config`. That said, using XDG-style config storage _is_ possible in macOS but I'd rather comply with the OS's own guidance here.

**Comment by zkat** [comment]
Other thoughts: We should add a `dotnet nuget config-path` command or something similar so customers scripting things around NuGet can portably get the correct config file on each platform (`$ cat $(dotnet nuget config-path)`)

**Comment by JonDouglas** [comment]
@zkat I think the MacOS callout is a good one. Do you think this should apply for CLI/headless experiences given NuGet isn't really an installable app per-say for end users? There's a good section on hidden files & directories in [the same documentation about Simplifying the User Experience](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW7) which suggests that the Linux proposal should still be ideal for the CLI experience / software developers:

**UNIX-specific directories.** The directories in this category are inherited from traditional UNIX installations. They are an important part of the system’s BSD layer but are **_more useful to software developers than end users_**. Some of the more important directories that are hidden include:
- /bin—Contains essential command-line binaries. Typically, you execute these binaries from command-line scripts.
- /dev—Contains essential device files, such as mount points for attached hardware.
- /etc—Contains host-specific configuration files.
- /sbin—Contains essential system binaries.
- /tmp—Contains temporary files created by apps and the system.
- /usr—Contains non-essential command-line binaries, libraries, header files, and other data.
- /var—Contains log files and other files whose content is variable. (Log files are typically viewed using the Console app.)

Another proposal would be:

`XDG_CONFIG_HOME` would likely map to `~/Library/Preferences/` which would potentially pollute the user's app preference space for a CLI experience.

Java for example puts these preferences in the location above.

**Comment by heng-liu** [comment]
For now, NuGet maintains a [SpecialFolder Enum](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/PathUtil/NuGetEnvironment.cs#L338) and complex logics to map different folders on different platforms in .NET Core code path (.NET Framework code path is different, it uses Environment.SpecialFolder from .NET Framework ):
(The code is : https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/PathUtil/NuGetEnvironment.cs#L86-L164)

The reason why NuGet maintains a SpecialFolder ourselves seems like there is [no such Enum in .NET core before](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/PathUtil/NuGetEnvironment.cs#L333-L337 ) 

But since .NET Core start to support Environment.SpecialFolder from netcoreapp2.0, shall we use [Environment.SpecialFolder Enum in .NET Core](https://docs.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=net-5.0) instead of making a enum ourselves and maintain complex logics of mapping different folders on different platforms in .NET Core code path?

If we use that enum of .NET, we just let the .NET to decide which folder to pick on different platforms. 
e.g. NuGet could get user wide settings by picking Environment.SpecialFolder.ApplicationData folder and then check the subfolder named "NuGet".

**Comment by nkolev92** [comment]
@heng-liu 

The special folder logic is hidden so it should be safe to refactor. 
Since netstandard2.0 added support for Environment.SpecialFolder, it should be safe to change to using that instead. 
We should just verify that the experience is consistent and that there are no surprises.

**Comment by heng-liu** [comment]
Thanks @nkolev92 !
I'll compare the two and post the results here.

**Comment by heng-liu** [comment]
Since only .NET Core code path will be changed, 
I compared `System.Environment.GetFolderPath(System.Environment.SpecialFolder._SomeFolder_)`
and `NuGetEnvironment.GetFolderPath(NuGetEnvironment.SpecialFolder._SomeFolder_)` on Windows/Linux/Mac for the .NET Core for all the 6 folders.

On Windows, everything is the same:
```
ProgramFilesX86 in .NET,  C:\Program Files (x86)
ProgramFilesX86 in NuGet,  C:\Program Files (x86)

ProgramFiles in .NET,  C:\Program Files
ProgramFiles in NuGet,  C:\Program Files

UserProfile in .NET,  C:\Users\henli
UserProfile in NuGet,  C:\Users\henli

CommonApplicationData in .NET,  C:\ProgramData
CommonApplicationData in NuGet,  C:\ProgramData

ApplicationData in .NET,  C:\Users\henli\AppData\Roaming
ApplicationData in NuGet,  C:\Users\henli\AppData\Roaming

LocalApplicationData in .NET,  C:\Users\henli\AppData\Local
LocalApplicationData in NuGet,  C:\Users\henli\AppData\Local
```
On Linux, **CommonApplicationData** and **ApplicationData** are different:

```
ProgramFilesX86 in .NET,
ProgramFilesX86 in NuGet,

ProgramFiles in .NET,
ProgramFiles in NuGet,

UserProfile in .NET,  /home/henli
UserProfile in NuGet,  /home/henli

CommonApplicationData in .NET,  /usr/share
CommonApplicationData in NuGet,  /etc/opt

ApplicationData in .NET,  /home/henli/.config
ApplicationData in NuGet,  /home/henli/.nuget

LocalApplicationData in .NET,  /home/henli/.local/share
LocalApplicationData in NuGet,  /home/henli/.local/share
```
On MacOS, **ProgramFiles**, **CommonApplicationData** and **ApplicationData** are different:
```
ProgramFilesX86 in .NET,
ProgramFilesX86 in NuGet,

ProgramFiles in .NET,  /Applications
ProgramFiles in NuGet,

UserProfile in .NET,  /Users/heng
UserProfile in NuGet,  /Users/heng

CommonApplicationData in .NET,  /usr/share
CommonApplicationData in NuGet,  /Library/Application Support

ApplicationData in .NET,  /home/henli/.config
ApplicationData in NuGet,  /home/henli/.nuget

LocalApplicationData in .NET,  /home/henli/.local/share
LocalApplicationData in NuGet,  /home/henli/.local/share
```
For all those differences, does .NET special folder value make sense? 
(.NET references document https://www.freedesktop.org/software/systemd/man/file-hierarchy.html)

The code from .NET is as following:
Unix : https://github.com/dotnet/runtime/blob/c97fafd09fe358129ee3bdeb4ba76cd1c111e8cb/src/libraries/System.Private.CoreLib/src/System/Environment.GetFolderPathCore.Unix.cs#L57-L144

We use ApplicationData for user wide NuGet.Config, and we're going to change the current home/.nuget folder, to use the value of env var XDG_CONFIG_HOME, if it's null, then we will get from home/.config. After this change, it will be the same with what we get from .NET: `System.Environment.GetFolderPath(System.Environment.SpecialFolder.ApplicationData)`

But how about CommonApplicationData ?

**Comment by nkolev92** [comment]
`CommonApplicationData` seems to be used for MachineWide settings, so my gut instinct is we shouldn't change that. 
That one is consistent among mono and .NET Core, so that's all that matters imo.

**Comment by heng-liu** [comment]
The implementation needs the symbolic link API, which is proposed at https://github.com/dotnet/runtime/issues/24271

**Comment by lewing** [comment]
cc @sandyarmstrong re https://github.com/NuGet/Home/issues/5555

**Comment by JonDouglas** [comment]
@heng-liu Would you be able to assign appropriate reviewers to this proposal so we can merge? There's a few individuals on this PR who can help review in addition. If we can't merge and should close this instead, feel free to close this out!

**Comment by zivkan** [comment]
The dotnet/runtime repo finished their symbolic link APIs work, however, they didn't make it a package that we can use on .NET Framework/Mono.  Therefore, for this design to be implemented, NuGet would need to P/Invoke symlink APIs on relevant platforms. Otherwise, this feature need to be redesigned to not depend on symlink APIs in the runtime.

**Comment by jeffkl** [comment]
Team Review: Closing stale PRs, please feel free to re-open when this work continues

**Pull request closed without merging**
