### PR TITLE
VSDeprecation Feature review

### PR DESCRIPTION
**Pull request by meeraharidasa**

### CODE REVIEW

**Comment by ghost** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/NuGet/Home?pullRequest=10863) <br/>All CLA requirements met.

**Comment by JonDouglas** [comment]
Thank you so much for the contribution to NuGet!

We'll leave this proposal open for the next couple weeks to get feedback from the .NET community & respective teams & we'll do a quick internal review after!

If you're seeing this message, please 👍 or provide your feedback on this proposal in this PR as to why we should or shouldn't do this.

Thank you everyone!

**Review by JonDouglas — APPROVED** [review]
We reviewed this proposal this afternoon and have decided to approve it to improve the deprecation story in Visual Studio. Thank you for your contribution!

**Comment by JonDouglas** [comment]
Thank you so much for the contribution! We took some time today to review the proposal and have decided to accept the proposal as we gear up to take on the work. We believe these enhanced experiences will provide a better deprecation story for our users and we'll keep you in the loop as we progress.

**Pull request merged**
