### PR TITLE
Move issue triaging policy to accepted folder

### PR DESCRIPTION
**Pull request by heng-liu**
Since https://github.com/NuGet/Home/pull/11719 is approved, I'd move the issue triaging policy from "proposed" folder to "accepted" folder.

### CODE REVIEW

**Comment by heng-liu** [comment]
FYI @JonDouglas @anangaur @aortiz-msft

**Review by zivkan — APPROVED** [review]

**Review by JonDouglas — APPROVED** [review]

**Comment by nkolev92** [comment]
Should we have a version of this that's not in a proposal form and sits at the root of our repo to improve discoverability?
Ideally the README can point to this as well.

**Comment by JonDouglas** [comment]
Yes please. Either in the wiki or repo sounds good to me. Then we can update readme

**Comment by nkolev92** [comment]
https://github.com/NuGet/Home/pull/11835

**Pull request merged**
